version: '3.8'

services:
  shard1:
    image: mariadb:10.6
    container_name: shard1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zipcodes
      MYSQL_USER: maxuser
      MYSQL_PASSWORD: maxpwd
    volumes:
      - ./shard1.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4001:3306"

  shard2:
    image: mariadb:10.6
    container_name: shard2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zipcodes
      MYSQL_USER: maxuser
      MYSQL_PASSWORD: maxpwd
    volumes:
      - ./shard2.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4002:3306"

  maxscale:
    build:
      context: ./maxscale
      dockerfile: Dockerfile
    container_name: maxscale
    depends_on:
      - shard1
      - shard2
    ports:
      - "4006:4006"  # Listener port for MyService
    volumes:
      - ./example.cnf:/etc/maxscale.cnf

