#version: '3.8'

services:
  shard1:
    image: mariadb:10.6
    container_name: shard1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: maxuser
      MYSQL_PASSWORD: maxpwd
    ports:
      - "3307:3306"
    volumes:
      - ./shard1.sql:/docker-entrypoint-initdb.d/init.sql:ro

  shard2:
    image: mariadb:10.6
    container_name: shard2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: maxuser
      MYSQL_PASSWORD: maxpwd
    ports:
      - "3308:3306"
    volumes:
      - ./shard2.sql:/docker-entrypoint-initdb.d/init.sql:ro

  maxscale:
    image: mariadb/maxscale:latest
    container_name: maxscale
    depends_on:
      - shard1
      - shard2
    ports:
      - "4006:4006"   # MaxScale port
      - "8989:8989"   # MaxScale admin
    volumes:
      - ./maxscale.cnf.d/example.cnf:/etc/maxscale.cnf.d/example.cnf:ro
    command: ["maxscale", "-f", "/etc/maxscale.cnf.d/example.cnf", "-d"]

