#version: '2'
services:
  shard1:
    image: mariadb:10.3
    container_name: shard1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "4001:3306"

  shard2:
    image: mariadb:10.3
    container_name: shard2
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "4002:3306"

  maxscale:
    image: mariadb/maxscale:latest
    container_name: maxscale
    depends_on:
      - shard1
      - shard2
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf
    ports:
      - "4006:4006"

