#version: "3.8"

services:
  shard1:
    image: mariadb:10.6
    container_name: shard1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: maxuser
      MYSQL_PASSWORD: maxpwd
    ports:
      - "3307:3306"
    volumes:
      - ./shard1.sql:/docker-entrypoint-initdb.d/init.sql

  shard2:
    image: mariadb:10.6
    container_name: shard2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: maxuser
      MYSQL_PASSWORD: maxpwd
    ports:
      - "3308:3306"
    volumes:
      - ./shard2.sql:/docker-entrypoint-initdb.d/init.sql

  maxscale:
    build: 
      context: .
      dockerfile: Dockerfile  # This assumes your Dockerfile is named `Dockerfile` in the current directory
    container_name: maxscale
    depends_on:
      - shard1
      - shard2
    ports:
      - "4006:4006"   # MaxScale database port
      - "8989:8989"   # MaxScale admin port
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf:ro
    command: ["maxscale", "-f", "/etc/maxscale.cnf", "-d"]

