version: '2'

services:
  shard1:
    image: mariadb:10.3
    container_name: shard1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zipcodes_one
    volumes:
      - ./shard1.sql:/docker-entrypoint-initdb.d/init.sql
    command: --server-id=1
    ports:
      - "3307:3306"

  shard2:
    image: mariadb:10.3
    container_name: shard2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zipcodes_two
    volumes:
      - ./shard2.sql:/docker-entrypoint-initdb.d/init.sql
    command: --server-id=2
    ports:
      - "3308:3306"

  maxscale:
    image: mariadb/maxscale:latest
    container_name: maxscale
    depends_on:
      - shard1
      - shard2
    ports:
      - "4006:4006"
      - "8989:8989" # MaxScale admin API
    volumes:
      - ./maxscale.cnf.d:/etc/maxscale.cnf.d

