version: '3.8'

services:
  shard1:
    image: mariadb:10.6
    container_name: shard1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zipcodes_one
      MYSQL_USER: maxuser
      MYSQL_PASSWORD: maxpwd
    volumes:
      - ./shard1.sql:/docker-entrypoint-initdb.d/shard1.sql

  shard2:
    image: mariadb:10.6
    container_name: shard2
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zipcodes_two
      MYSQL_USER: maxuser
      MYSQL_PASSWORD: maxpwd
    volumes:
      - ./shard2.sql:/docker-entrypoint-initdb.d/shard2.sql

  maxscale:
    image: mariadb/maxscale:latest
    container_name: maxscale
    user: "1000:1000"
    depends_on:
      - shard1
      - shard2
    ports:
      - "4006:4006"
      - "8989:8989"
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf
    command: ["maxscale", "-f", "/etc/maxscale.cnf", "-d"]

