version: '3.8'

services:
  shard1:
    image: mariadb:10.3
    container_name: shard1
    environment:
      MYSQL_ROOT_PASSWORD: maxpwd
    volumes:
      - ./sql/shard1.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4001:3306"
    command: --server-id=1

  shard2:
    image: mariadb:10.3
    container_name: shard2
    environment:
      MYSQL_ROOT_PASSWORD: maxpwd
    volumes:
      - ./sql/shard2.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4002:3306"
    command: --server-id=2

  maxscale:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maxscale
    depends_on:
      - shard1
      - shard2
    volumes:
      - ./maxscale.cnf.d:/etc/maxscale.cnf.d
    ports:
      - "4006:4006"  # schemarouter (sharded read/write)
      - "8989:8989"  # REST API (optional)

