#version: '2'

services:
  shard1:
    image: mariadb:10.3
    container_name: shard1
    environment:
      MYSQL_ROOT_PASSWORD: maxpwd
    volumes:
      - ./init/shard1:/docker-entrypoint-initdb.d
    ports:
      - "4001:3306"

  shard2:
    image: mariadb:10.3
    container_name: shard2
    environment:
      MYSQL_ROOT_PASSWORD: maxpwd
    volumes:
      - ./init/shard2:/docker-entrypoint-initdb.d
    ports:
      - "4002:3306"

  maxscale:
    build: .
    container_name: maxscale
    depends_on:
      - shard1
      - shard2
    volumes:
      - ./maxscale/maxscale.cnf.d:/etc/maxscale.cnf.d
    ports:
      - "4006:4006"

