version: '2'
services:
  shard1:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql/shard1:/docker-entrypoint-initdb.d
    ports:
      - "4001:3306"

  shard2:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql/shard2:/docker-entrypoint-initdb.d
    ports:
      - "4002:3306"

  maxscale:
    image: mariadb/maxscale:latest
    depends_on:
      - shard1
      - shard2
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf
    ports:
      - "4006:4006"  # Sharding port (service listener)

