#version: '3.8'

services:
  shard1:
    image: mariadb:10.6
    container_name: shard1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: zipcodes_one
    volumes:
      - ./shard1.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - maxnet

  shard2:
    image: mariadb:10.6
    container_name: shard2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: zipcodes_two
    volumes:
      - ./shard2.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - maxnet

  maxscale:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maxscale
    depends_on:
      - shard1
      - shard2
    ports:
      - "4006:4006"
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf
    networks:
      - maxnet

networks:
  maxnet:
    driver: bridge

