version: '2'

services:
  shard1:
    image: mariadb:10.3
    container_name: shard1
    environment:
      MYSQL_ROOT_PASSWORD: maxpwd
    volumes:
      - ./init/shard1.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4001:3306"

  shard2:
    image: mariadb:10.3
    container_name: shard2
    environment:
      MYSQL_ROOT_PASSWORD: maxpwd
    volumes:
      - ./init/shard2.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4002:3306"

  maxscale:
    image: mariadb/maxscale:latest
    container_name: maxscale
    depends_on:
      - shard1
      - shard2
    volumes:
      - ./maxscale/maxscale.cnf.d/example.cnf:/etc/maxscale.cnf.d/example.cnf
    ports:
      - "4006:4006"

